CREATE TABLE TB_USER(
	USER_ID VARCHAR(20) PRIMARY KEY
	,PASSWORD VARCHAR(200) NOT NULL
	,AUTHORITY VARCHAR(10)
	,USER_NM VARCHAR(50) NOT NULL
	,EMAIL VARCHAR(50)
	,TEL_NO VARCHAR(20)
	,EMP_NO VARCHAR(10)
	,GENDER  CHAR(1)
);

